### ISSUE TITLE
Glowing Dropped Items

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#14]
### Description

Add the  ability to `<item-serializer>`:
* glowing items
* colored glow
* custom display name

This would be for items that you drop on the ground

Useful for literally highlighting dropped items that are valuable, and different colors could be used for rarity and such. Requires ProtocolLib update to implement

### Configuration

```yaml
Item:
  Drop:
    Glow: <Color>
    Name: <Message>
```

### Payment

- [ ] I'm willing to pay for this feature
