### ISSUE TITLE
More options to particle trails.

### ISSUE THREAD

**Issue by DarkmanBree** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#16]
### Description

Missing features from CrackShotPlus.
I noticed this while I was remaking my Flamethrower and Rocket Launcher in WM, there's no random spread, speed, colored dust or minecraft block dust.
I couldn't make my flames flow from in to out without that.

These new trail features can work with LINE.

- Spread will randomly spread the particle as if it was used like this: **/particle flame ~ ~ ~ 1 1 1** (Which Minecraft calls the Delta in the command)
- Speed will give the particle some speed, so it can flow in or out the line in a random direction.
- Color is for particles that can have their color modified, uses RGB.
- Block_Color is for particles that have Minecraft blocks to modify their look, like block dust or block marker.

### Configuration

```yaml
Trail:
  Shape: LINE
  Shape_Data:
    Spread: <distance>
    Speed: <speed>
    Color: <R>-<G>-<B>
    Block_Color: <Block/Item name>
```

### Payment

- [ ] I'm willing to pay for this feature
