### ISSUE TITLE
Please add bedrock support with geysermc

### ISSUE THREAD

**Issue by yomanwasup** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#19]
### Description

Please add bedrock support with geysermc, even if the model is 2d, it's still better than having to look at feathers which feels awful atm

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```

### Payment

- [ ] I'm willing to pay for this feature
