### ISSUE TITLE
Off hand "Hand Model" + Skin

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#2]
### Description

When a player is holding a weapon, a packet based (fake) item should be put in the player's offhand. This would be a model that could appear to be physically holding the weapon. The hand model should be able to use the [WeaponMechanics Skin System](https://github.com/WeaponMechanics/MechanicsMain/wiki/Skins) which supports sprinting, reloading, etc.

We should also allow different color hands.

Paid for by: `ASTRICK#1775`

### Configuration

We would have a folder called `server > plugins >WeaponMechanicsCosmetics > Hands` which has:
```yaml
Hand_AK-47:
  Base_Item: <ItemSerializer> # this can be used to give the item a name/lore/whatever
  Skin: <SkinSerializer> # used WeaponMechanics skin to change based on sprint/reload/whatever
```

Then in the `server > plugins > WeaponMechanics > weapons > assault_rifles > ak-47.yml` file, we would have
```yaml
AK-47:
  Cosmetics:
    Off_Hand_Hand: "Hand_AK-47"
```
