### ISSUE TITLE
Smoke Bomb using Blocks 

### ISSUE THREAD

**Issue by CJCrafter** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#20]
### Description

An animated block texture (like a flower or dead bush used in a radius to create a smoke effect. This is more FPS-friendly than using particles but has the downside of replacing a vanilla block.

Note: Particle smokes **WILL** be added at a later date. 

### Configuration

```yaml
  Explosion:
    Smoke:
      Radius: 5
      Block: <BlockSerializer>
```

The `BlockSerializer` will be a new type of serializer that supports ItemsAdder blocks. 

### Payment

- [ ] I'm willing to pay for this feature
