### ISSUE TITLE
Guns Animations (Again)

### ISSUE THREAD

**Issue by RollexGrief** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#22]
### Description

Animations using custom model data change

As I have done, for example: 
https://vimeo.com/713684549
https://vimeo.com/715997841

My performance in SkriptLang:
https://pastebin.com/30MeEbkT 

Hope to see this feature either in this or the next addon. Willing to help in any way I can for the sake of developing the plugin.

### Configuration

```yaml
        Animations:
            Enabled: 1 #True/False (Just in Skript i have problems with True and False in my custom config so i'm using 1 and 0)
            StopAnimationAfterScopeChange: #Stops the animation after switching from the scope (needed for reload animations like the M24 from my first video)
            Wait: 0 #Timeout between frames (only for guns like M24 from my first video)
            DisableShootWhileReloadingStarted: 0 #Disable the animation at the start of reloading (necessary so that there are no problems between the firing and reloading animations)
            Shoot: 
                Default: #Default its non-scope mode
                    Single: #Single firemode
                        - "24|2" #Custom model data number | ticks for this frame
                        - "1|1" 
                    AutoAndBurst: #Auto and Burst firemodes
                        - "24|1"
                        - "1|1"
                Scope: 
                    Single:
                        - "25|2"
                        - "2|1"
                    AutoAndBurst:
                        - "25|1"
                        - "2|1"            
            Reload: #Reload animations during WeaponReloadEvent
                - "3|2" #Custom model data number | ticks for this frame
                - "4|2"
                - "5|2"
                - "6|2"
                - "7|2"
                - "8|2"
                - "9|2"
                - "8|2"
                - "7|2"
                - "6|2"
                - "10|2"
                - "11|2"
                - "12|1"
                - "13|1"
                - "14|1"
                - "15|1"
                - "16|1"
                - "17|1"
                - "18|1"
                - "19|2"
                - "20|2"
                - "21|2"
                - "22|2"
                - "23|2"
                - "1|1"
```

### Payment

- [ ] I'm willing to pay for this feature
