### ISSUE TITLE
Muzzleflash entity - CustomModelData

### ISSUE THREAD

**Issue by Nightshade73** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#23]
### Description

For the Muzzleflash feature, Id like to see CustomModelData be supported so I can retexture the item to suite the gameplay.

Additionally, the support for use of the Item_Serializer is an even better upgrade.

### Configuration

```yaml
  Cosmetics:
    Muzzle_Flash: <true/false>
        Item: <ItemSerializer>
```

### Payment

- [ ] I'm willing to pay for this feature
