### ISSUE TITLE
Changeable Trails like on CSP

### ISSUE THREAD

**Issue by Byxis** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#25]
### Description

Hello,

I would like to know if it is possible to put the functionality of equipping trails, to be able to change them without changing the weapon.
A system similar to CSP would be perfect ;)

Thanks in advance,
Byxis.

### Configuration

```yaml
Trails:
  Trails 1:
    ....
  Trails 2:
    ...
  etc.
```

### Payment

- [ ] I'm willing to pay for this feature
