### ISSUE TITLE
Inventory Bundle UI

### ISSUE THREAD

**Issue by Nightshade73** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#27]
### Description

In-game there is a in-development item called a bundle only accessible through the give command.
The item has a feature of a display UI within the players inventory.

![2023-01-16_15 54 24](https://user-images.githubusercontent.com/23036913/212772594-442fe9bb-76a6-4f66-b51f-674d3d725792.png)

I would like to be able to manipulate this display for use on weapons.
Examples: 
Indicate how much ammo is in the weapon / totally available
Indicate (when attachments are supported) what weapon attachments are on the weapon
List and display weapon skins
Indicate weapon statistics like K/D, Rounds fired etc...

Feature bounty $100 USD or Crypto equivalent.

### Configuration

```yaml
Weapon_GUI:
  Weapon_GUI_Enabled: <true/false>
  Slot_1: <amount>
  Slot_2: <amount>
  Slot_3: <amount>
  etc.
```

### Payment

- [X] I'm willing to pay for this feature
