### ISSUE TITLE
add a Cartesian coordinate system for Shape_Data

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#29]
### Description

add a Cartesian coordinate system for Shape_Data

### Configuration

```yaml
    Shape_Data:
      Radius: <distance>
      Points: <amount>
      Loops: <amount>
      Function_Y: <String>
      Function_Z: <String>
      Cache: <true/false>
```

### Payment

- [ ] I'm willing to pay for this feature
