### ISSUE TITLE
new Format Trail and fixs

### ISSUE THREAD

**Issue by EmSockz** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#30]
### Description

Parametric ShapeData only works when the player is rotated from -180 to 0 on the x-axis, but does not work when the player is rotated from 0 to 180 on the x-axis

new Format Trail:
Since you have added the ability to use a parametric function type (x, y) and consumers can do an X offset. It turns out that the problem is in the correct display of these functions. The player can use the aiming mode on the weapon or use the left and right hand. In this case, the correct particle display may not appear as the consumer needs it depending on whether the player is using right/left hand or aiming.

I wrote below how you can solve this problem in the config. Add conditions briefly.

### Configuration

```yaml
  Trail:
    Distance_Between_Particles: <distance>
    Hide_Trail_For: <distance>
    Shapes:
      - ShapeData{type=Parametric, function="func", radius=1.0, points=1, loops=1, cache=true, conditions=[playerMainHand=RIGHT]}
      - ShapeData{type=Parametric, function="func", radius=1.0, points=1, loops=1, cache=true, conditions=[playerMainHand=LEFT]}
      - ShapeData{type=Parametric, function="func", radius=1.0, points=1, loops=1, cache=true, conditions=[scoping=true]}
    Particle_Chooser: <STOP/RANDOM/LOOP>
    Particles:
      - <Particle1>
      - <Particle2>
      - <etc...>
```

### Payment

- [ ] I'm willing to pay for this feature
