### ISSUE TITLE
REDSTONE particles, Skin command and Hand feature issue (1.12.2-Spigot)

### ISSUE THREAD

**Issue by SSS31SSS** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#34]
### Has this issue already been reported? Did you ask for help before making this report?

- [X] I have searched the existing issues
- [X] I have asked for help

### Current Behavior

1- If I add REDSTONE particles to the particle section in the Trail section and use the /wm reload command, it will give an error in the console and the plugin will become unusable.

2- I set the test Skin, but after typing the /skin test command, nothing happens. It doesn't give an error on the console either. Finally, I think it would be more correct to use the /wmc skin command since the /skin command conflicts with the SkinRestorer plugin's command.

3- I'm trying to set the hand property, but the console says it doesn't set the default hand part.

### Expected Behavior

1- It should run without errors when adding the REDSTONE particles.

2- I want to see the image of the skin I set after using the /skin <skinname> or /wmc skin <skinname> command.

3- I would appreciate it if you could prepare a video about the hand and skin feature.

### Steps To Reproduce

1-   
```yml
  Trail:
    Distance_Between_Particles: 0.3
    Particle_Chooser: LOOP
    Particles:
      - "Particle{particle=REDSTONE, color=RED, size=0.4}"
```

2- 
```yml
  Skin:
    Default:
      Durability: 2
    Scope:
      Durability: 3
    Sprint:
      Durability: 4
    test:
      Default:
        Type: "GOLD_HOE"
        Durability: 5
      Scope:
        Type: "GOLD_HOE"
        Durability: 6
      Sprint:
        Type: "GOLD_HOE"
        Durability: 7
```

3-
```yml
  Hand:
    Item: 
      Type: "GOLD_HOE"
      Default:
        Type: "GOLD_HOE"
        Durability: 8
      Scope:
        Type: "GOLD_HOE"
        Durability: 9
      Sprint:
        Type: "GOLD_HOE"
        Durability: 10
    test:
      Default:
        Type: "GOLD_HOE"
        Durability: 8
      Scope:
        Type: "GOLD_HOE"
        Durability: 9
      Sprint:
        Type: "GOLD_HOE"
        Durability: 10
```

### Frequency

1- %100

2- %100

3- %100

### Version and Log

Plugin Version: WeaponMechanics-v2.1.4, MechanicsCore-2.1.2
WeaponMechanicsCosmetics Version: WeaponMechanicsCosmetics-2.0.8
Server: 1.12.2-Spigot | Java: 17

1- https://paste.gg/p/anonymous/c363dbdc0eb34ff3bd9092548dbd6b28 (REDSTONE particle error)

2- Nothing happens on console or in game.

3- https://paste.gg/p/anonymous/c98a7e6612bc42dd983abc540abc7d9c (Hand problem. Although it is the same as in the wiki, it gives this error in the console.)

**Comment by CJCrafter** [comment]
1. update server to latest for full support
2. update server to latest for full support
3. config error (spacing error)

fixed
```yaml
  Hand:
    Item: 
      Type: "GOLD_HOE"
    Default:
      Type: "GOLD_HOE"
      Durability: 8
    Scope:
      Type: "GOLD_HOE"
      Durability: 9
    Sprint:
      Type: "GOLD_HOE"
      Durability: 10
    test:
      Default:
        Type: "GOLD_HOE"
        Durability: 8
      Scope:
        Type: "GOLD_HOE"
        Durability: 9
      Sprint:
        Type: "GOLD_HOE"
        Durability: 10
```
