### ISSUE TITLE
AIMING

### ISSUE THREAD

**Issue by yomanwasup** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#35]
### Description

When you ADS (aim down sight), it would be nice if the player holds the weapons up to his face like when a player is pulling a bow.

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```

### Payment

- [ ] I'm willing to pay for this feature
