### ISSUE TITLE
Flesh

### ISSUE THREAD

**Issue by yomanwasup** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#36]
### Description

Toggle on and off flesh in weaponmechanicscosmetics:

When you shoot animals/mobs, red particles will appear/splatter to imitate taking damage irl.

3 toggle setting would be nice:
For mobs.
for animals
and for players.

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```

### Payment

- [ ] I'm willing to pay for this feature
