### ISSUE TITLE
Bedrock/geyser Support Texture Pack

### ISSUE THREAD

**Issue by yomanwasup** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#37]
### Description

Bedrock/GeyserMC support through a texture pack.
3D Gun texture packs are possible in bedrock, this is an example of a 3D gun pack, so they are possible to make with blockbench I'm guessing or through another method: https://www.planetminecraft.com/texture-pack/guns-3d-texturepack/

Yes, I'm willing to pay for this.

### Configuration

```yaml
My_Feature:
  Feature_Option: <true/false>
  Other_Option: <amount>
  etc.
```

### Payment

- [X] I'm willing to pay for this feature
