### ISSUE TITLE
Particle Mechanic

### ISSUE THREAD

**Issue by Herobrine15432** [WeaponMechanics/WeaponMechanicsCosmeticsWiki#5]
### Description

Add a Mechanic that works with particle to add for example particle when hitting something

### Configuration

```yaml
Mechanics:
  Particle: <>

**Comment by CJCrafter** [comment]
Already added, I just need to make the wiki for it:
```yaml
Mechanics:
  Particles:
    Particle_1:
      Type: <FLAME/CRIT/WHATEVER>
      Color: <ColorSerializer> # Can be used with REDSTONE, MOB_SPELL, DUST_COLOR_TRANSITION
      Fade_Color: <ColorSerializer> # Can only be used with DUST_COLOR_TRANSITION particles
      Size: <Float> # Can be used with REDSTONE, or DUST_COLOR_TRANSITION
      Count: <Integer> # usually the player should not define this
      Noise: <x-y-z>
      Velocity: <x-y-z, scalar (inherit velocity * scalar)>
      Material_Data: <ItemSerializer>
```
